<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class VinTableSeeder extends Seeder {

    public function run() {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('vins')->truncate();
        $i = rand(1, 2);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 1,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Syrah du Valais "Grand Métral"',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020-2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 1,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 2,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'Chablis du Village',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 12.5,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 3,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'Nuits-St-Croix « Vendanges Tardives »',
            'annee' =>'2009',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 1,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 4,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Nuits-St-Georges',
            'annee' =>'2013',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2016 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '1er cru Aux Boudots',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 5,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Corton-Bressandes « Grand Cru »',
            'annee' =>'2013',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2022 - 2043',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => 'Grand Cru',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 5,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Nuits-St-Georges',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2018 - 2028',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '1er cru Les Chênes Carteaux',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 4,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'MEURSAULT « Clos de Tavaux » ',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => 'Monopole AC 2015',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 5,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Etna Rosso DOC',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 14.5,
            'apogee' => '2017 - 2025',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 1,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 3,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Les Pruliers',
            'annee' =>'2016',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2026',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 1,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'CHABLIS « Les Vieilles Vignes »',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 12.5,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 5,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'La Comme',
            'annee' =>'2016',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '1er Cru',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 3,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Château les Cruzelles',
            'annee' =>'2015',
            'description' => 'Le Château Duhart-Milon Rothschild est un 4ème grand cru classé sur la commune de Pauillac à Bordeaux. Cette propriété de 75 ha appartient depuis 1962 à la branche française des Rothschild, celle qui est aussi propriétaire du Château Lafite-Rothschild, le célèbre 1er grand cru classé. L’assemblage est médocain classique avec environ 75% de Cabernet-Sauvignon pour 25% de Merlot. Depuis la fin des années 70, les vins du Château Duhart-Milon Rothschild ont retrouvé le lustre qui était le sien, lors du classement de 1855. Dans le style de leur grand frère, Lafite, les vins de Duhart Milon associent finesse et élégance.',
            'alcool' => 13.5,
            'apogee' => '2017 - 2027',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '4ème grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 3,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Château Grand Corbin-Despagne',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13.5,
            'apogee' => '2021 - 2045',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => 'Grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 4,
            'idType' => 1,
            'idStock' => $i,
            'nom' => '',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13.5,
            'apogee' => '2021 - 2045',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => 'Grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 5,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'Château les Justices',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13.5,
            'apogee' => '2018 - 2035',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '4ème grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 2,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'Château Boyd-Cantenac',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2025 - 2050',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '3ème grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 4,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Château Cambon la Pelouse',
            'annee' =>'2015',
            'description' => 'Figurant parmi les plus anciens châteaux du Médoc, la propriété expédie ses vins en Angleterre dès le XVIIe siècle et en Hollande à partir du XVIIIe siècle. Sous la révolution, le château a appartenu à la famille de Cambon, à qui il doit son nom. Le vignoble, entièrement décimé lors du gel de 1956 et partiellement transformé alors en champ céréalier, a été replanté en 1975 et a une moyenne d’âge d’une trentaine d’années.',
            'alcool' => 13.5,
            'apogee' => '2022 - 2038',
            'tempCons' => '13',
            'tempServ' => '14',
            'titre' => 'Cru Bourgeois supérieur',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 2,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Château Duhart-Milon Rothschild',
            'annee' =>'2015',
            'description' => 'Le Château Duhart-Milon Rothschild est un 4ème grand cru classé sur la commune de Pauillac à Bordeaux. Cette propriété de 75 ha appartient depuis 1962 à la branche française des Rothschild, celle qui est aussi propriétaire du Château Lafite-Rothschild, le célèbre 1er grand cru classé. L’assemblage est médocain classique avec environ 75% de Cabernet-Sauvignon pour 25% de Merlot. Depuis la fin des années 70, les vins du Château Duhart-Milon Rothschild ont retrouvé le lustre qui était le sien, lors du classement de 1855. Dans le style de leur grand frère, Lafite, les vins de Duhart Milon associent finesse et élégance.',
            'alcool' => 13.5,
            'apogee' => '2023 - 2040',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '4ème grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 1,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'Château Respide-Médeville',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13.5,
            'apogee' => '2018 - 2035',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '4ème grand cru classé',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 2,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Ribera Del Duero DO "Reserva"',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 14,
            'apogee' => '2018 - 2032',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 1,
            'idType' => 2,
            'idStock' => $i,
            'nom' => 'Château Smith Haut-Lafitte',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13.5,
            'apogee' => '',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 1,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 2,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Château Meyney',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2025 - 2046',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => 'Cru bourgeois supérieur',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 3,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Barolo « Castelletto »',
            'annee' =>'2011',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 14.5,
            'apogee' => '2019 - 2033',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 1,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 4,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Langhe Nebbiolo DOC',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2015 - 2020',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 0
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,  
            'idProd' => 5,
            'idType' => 1,
            'idStock' => $i,
            'nom' => 'Mount Hermon rouge',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        // roseys
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 4,
            'idType' => 3,
            'idStock' => $i,
            'nom' => 'Oeil de Perdrix',
            'annee' =>'2017',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 2,
            'idType' => 3,
            'idStock' => $i,
            'nom' => 'Dôle Blanche',
            'annee' =>'2018',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 3,
            'idType' => 3,
            'idStock' => $i,
            'nom' => 'Rosé de Gamay VdP Romand',
            'annee' =>'2017',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 1,
            'idType' => 3,
            'idStock' => $i,
            'nom' => 'Apologia Pink',
            'annee' =>'2017',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 5,
            'idType' => 3,
            'idStock' => $i,
            'nom' => 'Rosé de Gamay VdP Schwyz',
            'annee' =>'2017',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        // mousseux
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 3,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Champagne Charles Mignon',
            'annee' =>'2018',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '14',
            'tempServ' => '8',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 2,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Crémant Alsace',
            'annee' =>'2019',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 5,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Champagne Gonet-Médeville',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 4,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Prosecco di Valdobbiadene',
            'annee' =>'2014',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 3,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Champagne Taittinger',
            'annee' =>'2018',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 3,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Champagne Louis Roederer',
            'annee' =>'2018',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
        DB::table('vins')->insert([
            'idCondi' => 1,
            'idProd' => 3,
            'idType' => 4,
            'idStock' => $i,
            'nom' => 'Crémant Yverdon-les-Bains',
            'annee' =>'2015',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus ipsum, hendrerit non purus at, egestas malesuada nibh. Donec tempus eros non interdum posuere. Mauris gravida mauris a turpis consectetur, a vulputate enim molestie.',
            'alcool' => 13,
            'apogee' => '2020 - 2030',
            'tempCons' => '16',
            'tempServ' => '15',
            'titre' => '',
            'finDeSerie' => 0,
            'estBio' => 0,
            'estPrimeur' => 0,
            'estPromo' => 0,
            'estNouveau' => 1
        ]);
    }
}